### ISSUE TITLE
multiple shared tabs in y-codemirror

### ISSUE THREAD

**Issue by krishnarastogi** [yjs/y-codemirror#20]
Can we have multiple tabs in y-codemirror editor, just like the demo "y-quill-doc-list"?
https://docs.yjs.dev/getting-started/working-with-shared-types#managing-multiple-collaborative-documents-in-a-shared-type

**Comment by dmonad** [comment]
That should already work, right?

Or are you asking me to create another demo that shows how to do that with y-codemirror instead of y-quill?

**Comment by krishnarastogi** [comment]
hey @dmonad!
Thanks so much for your reply!

We have tried implementing the y-quill demo on y-codemirror, y-monaco and the drawing app and for some reason it is not working
If its not too much of work can you can share a small demo for the same on y-codemirror.

we are facing issues in the encoding the Ytext object into string.

`const documentList = ydoc.getArray('doc-list'); ` --> is creating the array

```
    const newDoc = new Y.Text();
    // Set initial content with the headline being the index of the documentList
    newDoc.applyDelta([
      { insert: `Document #${documentList.length}` },
      { insert: '\n', attributes: { header: 1 } },
      { insert: '\n' },
    ]);
    documentList.push([newDoc]);
```
 
 after this it is not pushing the new document in the documentlist, it is giving undefined/empty array.  
 
 Also, how to get the data from Ytext, it is givng the object but not giving string or json using the toJson or toString, we are getting null.

**Comment by dmonad** [comment]
How do you determine that the `documentlist` is undefined/empty? 

Can you please share a single reproducible code snipped that doesn't give the intended result?

**Comment by krishnarastogi** [comment]
Hey @dmonad!

here is the reproducible code link: https://x7yt6.csb.app/

on click on new tab it is not creating the new documents or syncing the document, we tried replicating the y-quill example but it is giving error.

**Comment by dmonad** [comment]
There are several things that are missing in the code. 

For once, you are not rendering the application after elements have been added to the `documentList`. 

You can even log the Y.Text elements.

![image](https://user-images.githubusercontent.com/5553757/154084291-3fbd3305-b8a9-4bfb-80b4-387fccf7c24d.png)

Just a tip: make sure that you handle events and don't only react to changes that you create. For example, you bind the Y.text instance to an editor after _you_ created it. However, you should listen to events on `documentList` instead (or on the event that is fired when you click on the document-button) and then bind the editor to a div instance.

Please have another look at the mainstream example and adapt your code accordingly (maybe without react at first).
