### ISSUE TITLE
Demo is broken

### ISSUE THREAD

**Issue by nsheff** [yjs/y-codemirror#23]
> Please save me some time and use the following template. In 90% of all issues I can't reproduce the problem because I don't know what exactly you are doing, in which environment, or which y-* version is responsible. Just use the following template even if you think the problem is obvious.

**Checklist**

* [x] Are you reporting a bug? Use github issues for bug reports and feature requests. For general questions, please use https://discuss.yjs.dev/
* [x] Try to report your issue in the correct repository. Yjs consists of many modules. When in doubt, report it to https://github.com/yjs/yjs/issues/

**Describe the bug**
The yjs codemirror demo does not show any editor

**To Reproduce**
1. Go to https://demos.yjs.dev/codemirror/codemirror.html
2. See error

**Expected behavior**
There should be a codemirror demo

**Environment Information**
 - Browser / Chrome and Firefox,

**Comment by RajarshiPrattipati** [comment]
Codemirror v6 uses EditorView and no longer exports default CodeMirror. Causing y-codemirror to not be compatible with latest dependancy pulled from yarn. This package is no longer usable out of the box.

**Comment by dmonad** [comment]
Thanks @nsheff, it's fixed now.

@RajarshiPrattipati Please look for y-codemirror.next if you want to use CodeMirror v6.
