### ISSUE TITLE
destroy() fails if awareness not passed to the constructor

### ISSUE THREAD

**Issue by aslakhellesoy** [yjs/y-codemirror#7]
From what I can tell the `awareness` constructor argument is optional (there is an `if(awareness)`).

However, it is not optional when `destroy` is called. It will fail if `awareness` wasn't passed to the constructor.

**Comment by dmonad** [comment]
Right on. Thanks

**Comment by aslakhellesoy** [comment]
Wow that was fast! I was going to send you a PR but you beat me to it :-)

**Comment by dmonad** [comment]
Oh darn :sweat_smile: maybe next time!
