### ISSUE TITLE
Optionally disable blur handler

### ISSUE THREAD

**Issue by gmanriqueUy** [yjs/y-codemirror#8]
Currently, there's a `_blurListener` method that is attached to the `blur` event of Codemirror, which sets the cursor to `null`.

In my case, I would like the cursor to remain rendered even if I blur from the editor.

How can achieve that behavior?

Thanks in advance!

P.S. Excellent work with `yjs`! It's awesome!

**Comment by dmonad** [comment]
Hey @gmanriqueUy , you could create a PR with an option to disable that behavior.
