### ISSUE TITLE
Custom dom element for remote cursors

### ISSUE THREAD

**Issue by aslakhellesoy** [yjs/y-codemirror#9]
**Checklist**

[ ] Are you reporting a bug? Use github issues for bug reports and feature requests. For general questions, please use https://discuss.yjs.dev/
[x] Try to report your issue in the correct repository. Yjs consists of many modules. When in doubt, report it to https://github.com/yjs/yjs/issues/

**Is your feature request related to a problem? Please describe.**
In order to make my application feel more social I would like to display a (gr)avatar in remote cursors.

**Describe the solution you'd like**
It would be nice to be able to pass an optional `createRemoteCaret` function to the `CodemirrorBinding` constructor

Would you be interested in a pull request for this?

**Comment by dmonad** [comment]
Hey @aslakhellesoy , yeah sure always :-)

Sorry for coming back so late.
